kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mysqlbackup
  namespace: mysql
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
  namespace: mysql
roleRef:
  kind: Role
  name: mysqlbackup
  apiGroup: rbac.authorization.k8s.io

