apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: mysql-innodb
  namespace: mysql
spec:
  members: 3
  rootPasswordSecret: 
    name: root-password
  version: 8.0.13 ### this value should be same as the image tag present in the repository ###          
  config:                                
    name: innodb-mycnf
  volumeClaimTemplate:
    metadata:
      name: pvcdata
    spec:
      storageClassName: mysql-sc
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
  backupVolumeClaimTemplate:
    metadata:
      name: pvcbackup
    spec:
      storageClassName: mysql-sc
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi

