apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-operator-config
  namespace: {{.Values.operator.namespace}}
  labels:
    app: mysql-operator
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  mysql-operator-config.yaml: |
    images:
      mysqlServer: avashkumar/myprivaterepo   ### use avashkumar/mysql-innodb & tag=8.0.13 in Cluster.yaml for demo ###
      mysqlAgent: avashkumar/mysql-agent

